language: node_js
node_js:
  - lts/*
cache:
  yarn: true
  directories:
    - public
    - .cache
install:
  - yarn
script:
  - yarn build 
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master