version: '3.9'
### Service Conf ###
# NOT suitable for production - dev only
services:

### Auth / User Service ###
    vue-forum-auth:
        container_name: vue-forum-auth
        restart: always
        build: 
            context: packages/vue-forum-auth
            dockerfile: Dockerfile.dev
        command: npm run dev
        environment:
            - AUTH_PORT=5000
            - AUTH_MONGO_CONN_STR=mongodb://vue-forum-auth-db:27017/auth
        volumes:
            - ./packages/auth:/home/node/app
            - auth_node_modules:/home/node/app/node_modules
            - logs:/home/node/app/logs
        depends_on:
            - vue-forum-auth-db
        networks:
            - vue-forum-bridge

### Auth / User DB ###
    vue-forum-auth-db:
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=auth
        ports:
            - 27017:27017
        volumes:
            - vue_forum_auth_db:/data/db:delegated
        networks:
            - vue-forum-bridge

### Vue Client ###
    vue-forum-client:
        container_name: vue-forum-client
        build:
            context: packages/client
            dockerfile: Dockerfile.dev
        # command: /bin/bash -c "./wait-for-it.sh vue-forum-auth:5000 --timeout=60 -- npm run build && npm run start"
        volumes:
            - ./packages/vue-forum-client:/home/node/app
            - client_node_modules:/home/node/app/node_modules
        networks:
            - vue-forum-bridge
        depends_on:
            - vue-forum-auth

### Load Balancer / Ingress ###
    nginx: 
        restart: always
        build: 
            context: infra/ingress
            dockerfile: Dockerfile.dev
        ports:
            - "80:80"
        networks:
            - vue-forum-bridge
        depends_on:
            - vue-forum-client

### Base Network Conf ###
networks:
    vue-forum-bridge:
        driver: bridge
        
### Persistent Volumes ###
volumes:

### Auth Service Vols ###
    auth_node_modules: 
    logs:
    vue_forum_auth_db:
    
### Client Vols ###
    client_node_modules:
    