version: "3.9"
### Service Conf ###
# NOT suitable for production - dev only
services:

### Auth / User Service ###
  vue-forum-auth:
    container_name: vue-forum-auth
    restart: always
    build:
      context: .
      dockerfile: ./infra/docker/Dockerfile.auth.dev
      target: development
    working_dir: /var/build/packages/auth
    env_file: 
      - example.env
    volumes:
      - ./packages/auth/src:/var/build/packages/auth/src:delegated
      - ./packages/common:/var/build/packages/common:delegated
    depends_on:
      - vue-forum-auth-db
    ports:
      - 5000:5000
    networks:
      - vue-forum-bridge
    command: yarn run dev

### Auth / User DB ###
  vue-forum-auth-db:
    image: mongo:latest
    container_name: vue-forum-auth-db
    restart: always
    command: mongod --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - vue_forum_auth_db:/data/db:delegated
    ports:
      - 27017:27017
    networks:
      - vue-forum-bridge


### Vue Client ###
  vue-forum-client:
    container_name: vue-forum-client
    build:
      context: .
      dockerfile: ./infra/docker/Dockerfile.client.dev
    working_dir: /var/build/packages/client
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./packages/client/src:/var/build/packages/client/src:delegated
      - ./packages/client/config:/var/build/packages/client/config:delegated
      - client_node_modules:/var/build/packages/auth/node_modules
    networks:
      - vue-forum-bridge
    depends_on:
      - vue-forum-auth
    ports:
      - 3000:3000
    command: yarn run dev

### Load Balancer / Ingress ###
  nginx:
    restart: always
    build:
      context: ingress
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    networks:
      - vue-forum-bridge
    depends_on:
      - vue-forum-client

### Base Network Conf ###
networks:
  vue-forum-bridge:
    driver: bridge

### Persistent Volumes ###
volumes:
  logs:
  vue_forum_auth_db:
  client_node_modules:
