version: '3.9'
### Service Conf ###
# NOT suitable for production - dev only
services:

### Shared Dependencies ###
    vue-forum-base:
        container_name: vue-forum-base
        image: exbotanical/vue-forum-base
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - shared_cache:/usr/local/share/.cache
        
### Auth / User Service ###
    vue-forum-auth:
        extends: 
            service: vue-forum-base
        container_name: vue-forum-auth
        restart: always
        build:
            context: packages/auth
            dockerfile: Dockerfile.dev
        command: yarn run dev
        environment:
            - AUTH_PORT=5000
            - AUTH_MONGO_CONN_STR=mongodb://vue-forum-auth-db:27017/auth
        volumes:
            - ./packages/auth:/base/packages/auth
            - logs:/base/packages/auth/logs
        depends_on:
            - vue-forum-auth-db
        ports:
            - 5000:5000
        networks:
            - vue-forum-bridge

### Auth / User DB ###
    # TODO ADD WAIT SCRIPT
    vue-forum-auth-db:
        image: mongo:latest
        container_name: vue-forum-auth-db
        restart: always
        command: mongod --quiet --logpath /dev/null
        environment:
            - MONGO_INITDB_DATABASE=auth
        volumes:
            - vue_forum_auth_db:/data/db:delegated
        ports:
            - 27017:27017
        networks:
            - vue-forum-bridge

### Vue Client ###
    # vue-forum-client:
    #     container_name: vue-forum-client
    #     build:
    #         context: packages/client
    #         dockerfile: Dockerfile.dev
    #     # command: /bin/bash -c "./wait-for-it.sh vue-forum-auth:5000 --timeout=60 -- npm run build && npm run start"
    #     volumes:
    #         - ./packages/vue-forum-client:/base/packages/client
    #         - client_node_modules:/base/packages/client/node_modules
    #     networks:
    #         - vue-forum-bridge
    #     depends_on:
    #         - vue-forum-auth

### Load Balancer / Ingress ###
    # nginx: 
    #     restart: always
    #     build: 
    #         context: ingress
    #         dockerfile: Dockerfile.dev
    #     ports:
    #         - "80:80"
    #     networks:
    #         - vue-forum-bridge
    #     depends_on:
    #         - vue-forum-client

### Base Network Conf ###
networks:
    vue-forum-bridge:
        driver: bridge
        
### Persistent Volumes ###
volumes:
    shared_cache:
### Auth Service Vols ###
    auth_node_modules: 
    logs:
    vue_forum_auth_db:
    
### Client Vols ###
    # client_node_modules:
    