apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: lan-monitor/auth
---
apiVersion: v1
kind: service
metadata:
  name: auth-srv 
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: tcp
      port: 5000
      targetPort: 5000